---
title: "**Preregistration Protocol:** `r params$answers[[2]]`"
params:
  authors: NA
  orcid: NA
  answers: NA
  questions: NA
  metadata: NA
---
````{r, include = FALSE}
Sys.setlocale("LC_TIME", "English") # we want the date to be displayed in English
```` 

---
date: '`r format(Sys.time(), "%B %d, %Y at %H:%M")`^*'
---
\footnotetext{* This is not an official timestamp. The timestamp will be assigned upon submission to PsychArchives.}

````{r, echo = FALSE, results = 'asis'}
cat("## Author/s:", "\n\n")
for (i in 1:length(params$authors)){
  cat(params$authors[[i]], ", ORCID ID: ", params$orcid[[i]], "\n\n", sep ="")
}
````

````{r, echo = FALSE, results = 'asis'}

cat("## About: ","\n\n")
cat(" __Template version:__ ", params$answers[[2]], sep ="")
cat("This study protocol is based on the preregistration template for scoping reviews (https://doi.org/10.23668/psycharchives.5631).", "\n\n", sep ="")

````

\newpage

````{r, echo = FALSE, results = 'asis'}

for (i in 1:length(params$answers)) # loop durch alle items
{
  if(grepl("hxxd_", params$questions[[i]])) # find the headings (marked wit "hxxd_")
  {
    cat("\\newpage", sub("hxxd_", "# ", params$questions[[i]]), "\n\n") #start new page before each heading
  }
  
  else if (is.list(params$answers[[i]]))  # matrix item - ACHTUNG! Passt nur auf dieses eine Matrix Item 
  {
    for (a in names(params$answers[[i]])) 
      {
        if (is.null(params$answers[[i]][[a]]))
        {
          cat(a)
          cat(": no response", "\n\n")
        }
        else
        {
          if (params$answers[[i]][[a]] == "none") 
            {
            cat("The ", a, " will not be made accessible.", "\n\n", sep ="")
            }
          else if (params$answers[[i]][[a]] == "not applicable")
            {
            cat("The study will not involve ", a, ".\n\n", sep ="") 
            }
          else 
            {
            cat(a, " will be shared ", params$answers[[i]][[a]], ".\n\n", sep ="")
            }
        }
    }
  }
  else if (is.logical(params$answers[[i]])) # TRUE/FALSE items
  {
   # cat("**Item:** ", params$questions[[i]], "\n\n")
    cat("##", params$questions[[i]], "\n\n")
    if (params$answers[[i]] == TRUE)
    {
      cat(params$answers[[i]],  "\n\n")
    }
    else
    {
      cat("**Answer:** ", "No",  "\n\n")
    }
  }
  else
  {
    cat("##", params$questions[[i]], "\n\n") # Text items
    cat(params$answers[[i]],  "\n\n")
  }
}
cat("# License", "\n\n") # Text items
cat("This document was created using", "\n\n", sep ="")
cat("1) the Psychological Research Preregistration-Quantitative (aka PRP-QUANT) Template, version 2 (https://doi.org/10.23668/psycharchives.4584", "\n\n", sep ="")
cat("2) the PRISMA-ScR checklist (http://www.prisma-statement.org/documents/PRISMA-ScR-Fillable-Checklist_11Sept2019.pdf)
From: Tricco, A. C., Lillie, E., Zarin, W., O'Brien, K. K., Colquhoun, H., Levac, D., ... & Straus, S. E. (2018). PRISMA extension for scoping reviews (PRISMA-ScR): checklist and explanation. Annals of internal medicine, 169(7), 467-473. DOI: 10.7326/M18-0850).", "\n\n", sep ="")

cat("The implementation as Shiny app was done by ZPID. Find out more about ZPID and our preregistration service PreReg by visiting https://leibniz-psychology.org/ and http://prereg-psych.org/, respectively. To receive a timestamp and a citable DOI, submit your preregistration protocol as a PDF to PsychArchives via https://pasa.psycharchives.org/.", "\n\n", sep ="")
````

